//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_Homework_2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsForms_Homework_2.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string en_amount {
            get {
                return ResourceManager.GetString("en_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Color.
        /// </summary>
        internal static string en_changeColor {
            get {
                return ResourceManager.GetString("en_changeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca Cola.
        /// </summary>
        internal static string en_cocaCola {
            get {
                return ResourceManager.GetString("en_cocaCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string en_cost {
            get {
                return ResourceManager.GetString("en_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string en_count {
            get {
                return ResourceManager.GetString("en_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Total Price.
        /// </summary>
        internal static string en_countTotalPrice {
            get {
                return ResourceManager.GetString("en_countTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en_english {
            get {
                return ResourceManager.GetString("en_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Fries.
        /// </summary>
        internal static string en_frenchFries {
            get {
                return ResourceManager.GetString("en_frenchFries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamburger.
        /// </summary>
        internal static string en_hamburger {
            get {
                return ResourceManager.GetString("en_hamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot-Dog.
        /// </summary>
        internal static string en_hotDog {
            get {
                return ResourceManager.GetString("en_hotDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l..
        /// </summary>
        internal static string en_l {
            get {
                return ResourceManager.GetString("en_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Cafe.
        /// </summary>
        internal static string en_miniCafe {
            get {
                return ResourceManager.GetString("en_miniCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        internal static string en_petrol {
            get {
                return ResourceManager.GetString("en_petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string en_price {
            get {
                return ResourceManager.GetString("en_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuelling.
        /// </summary>
        internal static string en_refuelling {
            get {
                return ResourceManager.GetString("en_refuelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string en_russian {
            get {
                return ResourceManager.GetString("en_russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string en_settings {
            get {
                return ResourceManager.GetString("en_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        internal static string en_totalCost {
            get {
                return ResourceManager.GetString("en_totalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string ru_amount {
            get {
                return ResourceManager.GetString("ru_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить цвет.
        /// </summary>
        internal static string ru_changeColor {
            get {
                return ResourceManager.GetString("ru_changeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кока-Кола.
        /// </summary>
        internal static string ru_cocaCola {
            get {
                return ResourceManager.GetString("ru_cocaCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cтоимость.
        /// </summary>
        internal static string ru_cost {
            get {
                return ResourceManager.GetString("ru_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string ru_count {
            get {
                return ResourceManager.GetString("ru_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсчитать итоговую цену.
        /// </summary>
        internal static string ru_countTotalPrice {
            get {
                return ResourceManager.GetString("ru_countTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aнглийский.
        /// </summary>
        internal static string ru_english {
            get {
                return ResourceManager.GetString("ru_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жареный картофель.
        /// </summary>
        internal static string ru_frenchFries {
            get {
                return ResourceManager.GetString("ru_frenchFries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гамбургер.
        /// </summary>
        internal static string ru_hamburger {
            get {
                return ResourceManager.GetString("ru_hamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хот-дог.
        /// </summary>
        internal static string ru_hotDog {
            get {
                return ResourceManager.GetString("ru_hotDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to л..
        /// </summary>
        internal static string ru_l {
            get {
                return ResourceManager.GetString("ru_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мини Кафе.
        /// </summary>
        internal static string ru_miniCafe {
            get {
                return ResourceManager.GetString("ru_miniCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бензин.
        /// </summary>
        internal static string ru_petrol {
            get {
                return ResourceManager.GetString("ru_petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string ru_price {
            get {
                return ResourceManager.GetString("ru_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заправка.
        /// </summary>
        internal static string ru_refuelling {
            get {
                return ResourceManager.GetString("ru_refuelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string ru_russian {
            get {
                return ResourceManager.GetString("ru_russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string ru_settings {
            get {
                return ResourceManager.GetString("ru_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая стоимость.
        /// </summary>
        internal static string ru_totalCost {
            get {
                return ResourceManager.GetString("ru_totalCost", resourceCulture);
            }
        }
    }
}
